site_name:        RLEVectors.jl
repo_url:         https://github.com/phaverty/RLEVectors.jl
site_description: Run Length Encoded vectors for julia, inspired by BioConductor.
site_author:      phavertyp

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code

build: 'docs/build'

pages:
  - Home: build/index.md
  - Vignette: build/rlevectors_vignette.md
  - TODO: build/TODO.md
  - NEWS: build/NEWS.md
  - API: build/api.md
